version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
          GOPROXY: https://gocenter.io
    working_directory: /go/src/github.com/slok/grafterm
    steps:
      - checkout
      - run: make ci